#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v21
# autospec commit: e36a856
#
Name     : ddcutil
Version  : 2.2.0
Release  : 2
URL      : https://github.com/rockowitz/ddcutil/archive/v2.2.0/ddcutil-2.2.0.tar.gz
Source0  : https://github.com/rockowitz/ddcutil/archive/v2.2.0/ddcutil-2.2.0.tar.gz
Summary  : Control display settings
Group    : Development/Tools
License  : GPL-2.0 LGPL-3.0
Requires: ddcutil-bin = %{version}-%{release}
Requires: ddcutil-config = %{version}-%{release}
Requires: ddcutil-data = %{version}-%{release}
Requires: ddcutil-lib = %{version}-%{release}
Requires: ddcutil-license = %{version}-%{release}
Requires: ddcutil-man = %{version}-%{release}
BuildRequires : file
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(jansson)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(yaml-0.1)
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Starting with release 1.0.0, .gitignore specifies only files that should be
ignored by any ddcutil git repository, e.g. build artifacts. File of local
interest only should instead be specified in file .git/info/exclude, which
which unlike .gitignore is not tracked in the respository.

%package bin
Summary: bin components for the ddcutil package.
Group: Binaries
Requires: ddcutil-data = %{version}-%{release}
Requires: ddcutil-config = %{version}-%{release}
Requires: ddcutil-license = %{version}-%{release}

%description bin
bin components for the ddcutil package.


%package config
Summary: config components for the ddcutil package.
Group: Default

%description config
config components for the ddcutil package.


%package data
Summary: data components for the ddcutil package.
Group: Data

%description data
data components for the ddcutil package.


%package dev
Summary: dev components for the ddcutil package.
Group: Development
Requires: ddcutil-lib = %{version}-%{release}
Requires: ddcutil-bin = %{version}-%{release}
Requires: ddcutil-data = %{version}-%{release}
Provides: ddcutil-devel = %{version}-%{release}
Requires: ddcutil = %{version}-%{release}

%description dev
dev components for the ddcutil package.


%package lib
Summary: lib components for the ddcutil package.
Group: Libraries
Requires: ddcutil-data = %{version}-%{release}
Requires: ddcutil-license = %{version}-%{release}

%description lib
lib components for the ddcutil package.


%package license
Summary: license components for the ddcutil package.
Group: Default

%description license
license components for the ddcutil package.


%package man
Summary: man components for the ddcutil package.
Group: Default

%description man
man components for the ddcutil package.


%prep
%setup -q -n ddcutil-2.2.0
cd %{_builddir}/ddcutil-2.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739922773
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1739922773
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ddcutil
cp %{_builddir}/ddcutil-%{version}/COPYING %{buildroot}/usr/share/package-licenses/ddcutil/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/ddcutil-%{version}/icons/COPYING %{buildroot}/usr/share/package-licenses/ddcutil/ffd40814f94e4090dc25be1b090dd90b047e4e63 || :
cp %{_builddir}/ddcutil-%{version}/pixmaps/COPYING %{buildroot}/usr/share/package-licenses/ddcutil/ffd40814f94e4090dc25be1b090dd90b047e4e63 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ddcutil

%files config
%defattr(-,root,root,-)
/usr/lib/modules-load.d/ddcutil.conf
/usr/lib/udev/rules.d/60-ddcutil-i2c.rules

%files data
%defattr(-,root,root,-)
/usr/share/ddcutil/data/60-ddcutil-i2c.rules
/usr/share/ddcutil/data/60-ddcutil-usb.rules
/usr/share/ddcutil/data/90-nvidia-i2c.conf
/usr/share/ddcutil/data/nvidia-i2c.conf

%files dev
%defattr(-,root,root,-)
/usr/include/ddcutil_c_api.h
/usr/include/ddcutil_macros.h
/usr/include/ddcutil_status_codes.h
/usr/include/ddcutil_types.h
/usr/lib64/cmake/ddcutil/FindDDCUtil.cmake
/usr/lib64/libddcutil.so
/usr/lib64/pkgconfig/ddcutil.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libddcutil.so.5
/usr/lib64/libddcutil.so.5.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ddcutil/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/ddcutil/ffd40814f94e4090dc25be1b090dd90b047e4e63

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ddcutil.1
